---
- name: Update and upgrade packages 
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Replace the hostname entry with our own
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 {{ inventory_hostname }}"
    owner: root
    group: root
    mode: '0644'

- name: Install net-tools package
  apt:
    name: net-tools
    state: present

- name: Install OpenSSH server package
  apt:
    name: openssh-server
    state: present

- name: Enable UFW
  ufw:
    state: enabled

- name: Allow SSH traffic
  ufw:
    rule: allow
    port: 22
    proto: tcp


# - name: Disable cron e-mail notifications
#   cron:
#     name: MAILTO
#     user: root
#     env: yes
#     job: ""
